climate = read.csv("climate_change.csv",header = T)
training =subset(climate,Year <= 2006)
testing = subset(climate,Year > 2006)

model1 = lm(Temp ~ MEI + CO2 + CH4 + N2O + CFC.11 + CFC.12 + TSI + Aerosols, data=training)
summary(model1)
cor(training$N2O,training$MEI)
cor(training$N2O,training$CO2)
cor(training$N2O,training$CH4)
cor(training$N2O,training$CFC.11)
cor(training$N2O,training$CFC.12)
cor(training$N2O,training$TSI)
cor(training$N2O,training$Aerosols)
cor(training$CFC.11,training$MEI)
cor(training$CFC.11,training$CO2)
cor(training$CFC.11,training$CH4)
cor(training$CFC.11,training$N2O)
cor(training$CFC.11,training$CFC.12)
cor(training$CFC.11,training$TSI)
cor(training$CFC.11,training$Aerosols)
 
model2 = lm(Temp ~ MEI + N2O + TSI + Aerosols,data=training)
summary(model2)
?step
training_stp =step(model1)
summary(training_stp)

climate_predict = predict(training_stp,newdata =testing)
SSE = sum((climate_predict - testing$Temp)^2)
SST = sum((mean(training$Temp)- testing$Temp)^2)
R2_value = 1-(SSE/SST)
