IBM = read.csv("IBMStock.csv",header=T)
GE = read.csv("GEStock.csv", header=T)
ProcterGamble = read.csv("ProcterGambleStock.csv", header=T)
CocaCola = read.csv("CocaColaStock.csv", header=T)
Boeing = read.csv("BoeingStock.csv", header = T)
IBM$Date[1]
IBM$Date = as.Date(IBM$Date,"%m/%d/%y")
GE$Date = as.Date(GE$Date, "%m/%d/%y")
ProcterGamble$Date = as.Date(ProcterGamble$Date,"%m/%d/%y")
CocaCola$Date = as.Date(CocaCola$Date,"%m/%d/%y")
Boeing$Date = as.Date(Boeing$Date,"%m/%d/%y")
str(IBM)
summary(IBM)
mean(IBM$StockPrice)
min(GE$StockPrice)
max(CocaCola$StockPrice)
median(Boeing$StockPrice)
sd(ProcterGamble$StockPrice)
plot(CocaCola$Date,CocaCola$StockPrice,xlab="Date",ylab="Stockprice",main="CocaCola stocks",type="l")
lines(ProcterGamble$Date,ProcterGamble$StockPrice,col="blue")
abline(v=as.Date(c("2000-03-01")), lwd=0)
abline(v=as.Date(c("1983-01-01")), lwd=2)
plot(CocaCola$Date[301:432], CocaCola$StockPrice[301:432], type="l", col="red", ylim=c(0,210))
lines(IBM$Date[301:432],IBM$StockPrice[301:432],col="purple",lty=2)
lines(GE$Date[301:432],GE$StockPrice[301:432],col="blue",lty=1)
lines(ProcterGamble$Date[301:432],ProcterGamble$StockPrice[301:432],col="orange",lty=1)
lines(Boeing$Date[301:432],Boeing$StockPrice[301:432],col="black",lty=1)
abline(v=as.Date(c("2000-03-01")), lwd =0)
abline(v=as.Date(c("2004-01-01")), lwd =0)
abline(v=as.Date(c("2005-01-01")), lwd =0)
####Problem 4.1 &4.2
tapply(IBM$StockPrice,months(IBM$Date),mean)
tapply(GE$StockPrice,months(GE$Date),mean)
tapply(CocaCola$StockPrice,months(CocaCola$Date),mean)
