pisaTrain = read.csv("pisa2009train.csv",header = T)
pisaTest = read.csv("pisa2009test.csv", header = T)
summary(pisaTrain)

tapply(pisaTrain$readingScore,pisaTrain$male,mean)
pisaTrain = na.omit(pisaTrain)
pisaTest = na.omit(pisaTest)
pisaTrain$raceeth = relevel(pisaTrain$raceeth, "White")
pisaTest$raceeth = relevel(pisaTest$raceeth, "White")
lmscore = lm(pisaTrain$readingScore ~ .,data=pisaTrain)
summary(lmscore)
SSE =sum((lmscore$residuals)^2)
RMSE =sqrt(SSE/nrow(pisaTrain))

#stdAdata = subset(pisaTrain,pisaTrain$grade == 11)
#stdAtest =subset(pisaTest,pisaTest$grade ==11)
#stdBdata = subset(pisaTrain,pisaTrain$grade == 9)
#stdBtest =subset(pisaTest,pisaTest$grade == 9)
#lmscoreA = lm(stdAdata$readingScore ~.,data=stdAdata)
#stdA =predict(lmscoreA,newdata =stdAtest)
#lmscoreB =lm(stdBdata$readingScore~.,data=stdBdata)
#stdB = predict(lmscoreB,newdata = stdBtest)
#pmv =mean(stdA)-mean(stdB)

predTest = predict(lmscore,newdata =pisaTest)
summary(predTest)
SSEp =sum((predTest - pisaTest$readingScore)^2)
rmsep =sqrt(SSEp/nrow(pisaTest))

b=mean(pisaTrain$readingScore)
sstb = sum((b - pisaTest$readingScore)^2)
r2 = 1-(SSEp/sstb)
